name: Ubunt i386 arch fix
description: Allows to install i386 packages
branding:
  icon: message-circle
  color: green

inputs:
  install_wine:
    description: Install wine
    required: false
    default: "true"
  wine_fix_read_access_denied:
    description: Fix wine "Read access denied for device"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - run: |
        set -xeu -o pipefail
        $GITHUB_ACTION_PATH/gha.sh
      shell: bash
      env:
        INPUT_INSTALL_WINE: ${{ inputs.install_wine }}
        INPUT_WINE_FIX_READ_ACCESS_DENIED: ${{ inputs.wine_fix_read_access_denied }}
