name: Ubunt i386 arch fix
description: Allows to install i386 packages
branding:
  icon: message-circle
  color: green

inputs:
  install_wine:
    description: Install wine
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - run: |
        set -xeu -o pipefail
        $GITHUB_ACTION_PATH/gha.sh
      shell: bash
      env:
        INPUT_INSTALL_WINE: ${{ inputs.install_wine }}
